export const NigeriaStates = [
    {
        id: "Abia",
        name: "Abia",
        value: "Abia",
        label: "Abia"
    },
    {
        id: "Adamawa",
        name: "Adamawa",
        value: "Adamawa",
        label: "Adamawa",
    },
    {
        id: "Akwa-Ibom",
        name: "Akwa-Ibom",
        value: "Akwa-Ibom",
        label: "Akwa-Ibom",
    },
    {
        id: "Anambra",
        name: "Anambra",
        value: "Anambra",
        label: "Anambra",
    },
    {
        id: "Bauchi",
        name: "Bauchi",
        value: "Bauchi",
        label: "Bauchi",
    },
    {
        id: "Bayelsa",
        name: "Bayelsa",
        value: "Bayelsa",
        label: "Bayelsa",
    },
    {
        id: "Benue",
        name: "Benue",
        value: "Benue",
        label: "Benue",
    },
    {
        id: "Borno",
        name: "Borno",
        value: "Borno",
        label: "Borno",
    },
    {
        id: "Cross-River",
        name: "Cross-River",
        value: "Cross-River",
        label: "Cross-River",
    },
    {
        id: "Delta",
        name: "Delta",
        value: "Delta",
        label: "Delta",
    },
    {
        id: "Ebonyi",
        name: "Ebonyi",
        value: "Ebonyi",
        label: "Ebonyi",
    },
    {
        id: "Edo",
        name: "Edo",
        value: "Edo",
        label: "Edo",
    },
    {
        id: "Ekiti",
        name: "Ekiti",
        value: "Ekiti",
        label: "Ekiti",
    },
    {
        id: "Enugu",
        name: "Enugu",
        value: "Enugu",
        label: "Enugu",
    },
    {
        id: "Gombe",
        name: "Gombe",
        value: "Gombe",
        label: "Gombe",
    },
    {
        id: "Imo",
        name: "Imo",
        value: "Imo",
        label: "Imo",
    },
    {
        id: "Jigawa",
        name: "Jigawa",
        value: "Jigawa",
        label: "Jigawa",
    },
    {
        id: "Kaduna",
        name: "Kaduna",
        value: "Kaduna",
        label: "Kaduna",
    },
    {
        id: "Kano",
        name: "Kano",
        value: "Kano",
        label: "Kano",
    },
    {
        id: "Katsina",
        name: "Katsina",
        value: "Katsina",
        label: "Katsina",
    },
    {
        id: "Kebbi",
        name: "Kebbi",
        value: "Kebbi",
        label: "Kebbi",
    },
    {
        id: "Kogi",
        name: "Kogi",
        value: "Kogi",
        label: "Kogi",
    },
    {
        id: "Kwara",
        name: "Kwara",
        value: "Kwara",
        label: "Kwara",
    },
    {
        id: "Lagos",
        name: "Lagos",
        value: "Lagos",
        label: "Lagos",
    },
    {
        id: "Nasarawa",
        name: "Nasarawa",
        value: "Nasarawa",
        label: "Nasarawa",
    },
    {
        id: "Niger",
        name: "Niger",
        value: "Niger",
        label: "Niger",
    },
    {
        id: "Ogun",
        name: "Ogun",
        value: "Ogun",
        label: "Ogun",
    },
    {
        id: "Ondo",
        name: "Ondo",
        value: "Ondo",
        label: "Ondo",
    },
    {
        id: "Osun",
        name: "Osun",
        value: "Osun",
        label: "Osun",
    },
    {
        id: "Oyo",
        name: "Oyo",
        value: "Oyo",
        label: "Oyo",
    },
    {
        id: "Plateau",
        name: "Plateau",
        value: "Plateau",
        label: "Plateau",
    },
    {
        id: "Rivers",
        name: "Rivers",
        value: "Rivers",
        label: "Rivers",
    },
    {
        id: "Sokoto",
        name: "Sokoto",
        value: "Sokoto",
        label: "Sokoto",
    },
    {
        id: "Taraba",
        name: "Taraba",
        value: "Taraba",
        label: "Taraba",
    },
    {
        id: "Yobe",
        name: "Yobe",
        value: "Yobe",
        label: "Yobe",
    },
    {
        id: "Zamfara",
        name: "Zamfara",
        value: "Zamfara",
        label: "Zamfara",
    },
    {
        id: "FCT-Abuja",
        name: "FCT-Abuja",
        value: "FCT-Abuja",
        label: "FCT-Abuja",
    },
]